# Prometheus配置文件

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # 机器人自身指标
  - job_name: 'hypeliquid-bot'
    static_configs:
      - targets: ['hypeliquid-bot:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Prometheus自身指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 系统指标（如果启用node_exporter）
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
  # Docker指标（如果启用cadvisor）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s